### ISSUE TITLE
Could I contribute to this mod by translating it to polish?

### ISSUE THREAD

**Issue by Iwo24pl** [CitiesSkylinesMultiplayer/CS2M#2]
Yeah, ?

**Comment by popos123** [comment]
I can help too, I will make a translation review and check for eventually bugs if it appears.

**Comment by MrOmnes** [comment]
Hello, here it's french tranlastion if you want : 
[fr-FR.json](https://github.com/user-attachments/files/17292405/fr-FR.json)
